-- English Categories
INSERT INTO english_categories (id, category_name, created_at, question_count, updated_at)
VALUES 
(1, 'Synonyms', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(2, 'Antonyms', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(3, 'Idioms', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP),
(4, 'Correction of Sentences', CURRENT_TIMESTAMP, 4, CURRENT_TIMESTAMP),
(5, 'FITB with suitable words', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP),
(6, 'Spelling', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(7, 'Substitutes', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(8, 'Sequence', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP),
(9, 'Fill with correct form of verb', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP),
(10, 'Voice', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP);

-- Reasoning Categories
INSERT INTO reasoning_categories (id, category_name, created_at, question_count, updated_at)
VALUES 
(1, 'Alphabetical Series', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(2, 'Distances', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(3, 'Words which can be formed', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(4, 'Missing number in figures', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(5, 'Numerical Series', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(6, 'Cryptic Equations', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(7, 'Meaningful Order', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(8, 'Word Relations', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(9, 'Wrong Number in Series', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(10, 'Relations', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(11, 'Logical Reasoning', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(12, 'Directions', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(13, 'Folded Paper - Punched Holes', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(14, 'Positions', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(15, 'Groups of Persons', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(16, 'Odd One in the Group', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(17, 'Hidden Equations', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(18, 'Coded Words', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- QA Categories
INSERT INTO qa_categories (id, category_name, created_at, question_count, updated_at)
VALUES 
(1, 'Time and Work', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(2, 'Discounts', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(3, 'Ratio and Proportions', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(4, 'Profit and Loss', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(5, 'Time and Distance', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(6, 'Interest', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(7, 'Algebra', CURRENT_TIMESTAMP, 5, CURRENT_TIMESTAMP),
(8, 'Triangles', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(9, 'Circles', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(10, 'Trigonometry', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(11, 'Averages', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(12, 'Heights and Distances', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(13, 'Solids', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP);

-- GA Categories
INSERT INTO ga_categories (id, category_name, created_at, question_count, updated_at)
VALUES 
(1, 'Awards', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(2, 'Anatomy', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(3, 'Animals/Plants', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(4, 'Chemistry', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(5, 'Constitution', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(6, 'IT', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(7, 'Culture', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(8, 'Diseases', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(9, 'Economics', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(10, 'Geography', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(11, 'History H', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(12, 'History M', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(13, 'History B', CURRENT_TIMESTAMP, 2, CURRENT_TIMESTAMP),
(14, 'Physics', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(15, 'Religion', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(16, 'Sports', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(17, 'States', CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
(18, 'Miscellaneous', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP),
(19, 'Current Affairs', CURRENT_TIMESTAMP, 3, CURRENT_TIMESTAMP);

-- ROLES

INSERT INTO roles(name) VALUES ('ROLE_USER'), ('ROLE_MODERATOR'), ('ROLE_ADMIN');
